### ISSUE TITLE
situation:  taxi lights on

### ISSUE THREAD

**Issue by xplana** [skiselkov/BetterPushbackC#107]
i just thought about what would happen if a (..) pilot would turn on the taxi light(s) and blind the tug driver? 
would the driver immediately stop the pushback and ask the pilot to turn off the taxi lights?
do they (tug drivers) have some sort of shield to avoid something like that?

**Comment by skiselkov** [comment]
I've implemented a bunch of checks. PB refuses to start if you have landing/taxi lights on and if you turn them on during pushback, the driver yells at you and stops. For now the messages are text-only (with text-to-speech) and not full custom recordings.

**Comment by xplana** [comment]
very cool! this would be a good possibility to include some abusive language here:)

**Comment by skiselkov** [comment]
While the real world the driver might have a few choice words to throw your way, I'd like to keep this "family friendly" :)

**Comment by xplana** [comment]
:)

**Comment by skiselkov** [comment]
Implemented in v0.43, please test.

**Comment by JetNoise61** [comment]
yelling works nicely with the IXEG 733. ;-)
VERY minor thing: will driver be able to determin between Landing/Taxi Lights on prior yelling at me 
(a very future version maybe, haha). A matter of professionalism  ;-    ;-)

Thank you so much for this plugin and its getting better and better !!!!

**Comment by skiselkov** [comment]
@JetNoise61 Thanks for testing, closing this now. It already does this, yelling at you for the appropriate light type.

**Comment by xplana** [comment]
saso, this works great! Let the fun begin :)
I think this sneeds some more refinement: Currently, not all landing and taxi lights are discovered by the algorithm. 
I just did a fast cycle through some airplanes and it def. does not capture some light switches from the default b747, ff 757 and 767 as well as some lights of the ixeg 737.
see here an example for the ff767. But i can imagine this to become a mess if there is a need to individually handle each aircraft out there..

![bildschirmfoto 2017-08-18 um 11 13 32](https://user-images.githubusercontent.com/17392829/29453363-ab49da82-8409-11e7-9e1a-2cc1de4edd22.png)

I would also suggest to do a check prior to connecting the truck to the airplane if the respective lights are on or not. If i was a truck driver and if I would approach the aircraft (lineup) i would refuse to drive closer to the aircraft. Instead i would blow a horn and flash lights and finally speak to the pilot via the headset to turn the lights of. If might be way to dangerous to connect the truck while getting blind :-)
Hust a thought!

**Comment by skiselkov** [comment]
@xplana 
> Currently, not all landing and taxi lights are discovered by the algorithm.

This is a limitation of the generic approach. I'm checking the `sim/cockpit/electrical/landing_lights_on` and `sim/cockpit/electrical/taxi_light_on` datarefs. Whichever switch these datarefs are bound to is whichever switch we monitor. There is unfortunately no other way to detect other lights unless I would be willing to implement a huge table of per-aircraft-model animation datarefs (which I can assure I'm not willing to waste time on).

> I would also suggest to do a check prior to connecting the truck to the airplane if the respective lights are on or not.

Which is why as soon as you click "Start pushback" from the menu, BP automatically sets the light datarefs mentioned above to `0` (i.e. turning the lights off). That way we can be sure that the only reason the lights are on during pushback is because the user manually flipped them on. If the user then flips them back on, we won't stop for approach to the aircraft - I don't want to implement tiny details like this, the state transition engine is complicated enough as-is.

**Comment by JetNoise61** [comment]
Hi , okay tested it again, this time i got the correct yell. It didn't work the first time. Reason maybe:
I tested with Landing lights on first, ended this pushback and started a second one right after. This time Landing/OFF  Taxi/On . And it said "Landing light" ...
NEVERMIND, closed for me ;-)
