### ISSUE TITLE
Question about the LH Liveries

### ISSUE THREAD

**Issue by Milki52** [skiselkov/BetterPushbackC#133]
Hey, its me again, just a small question. 

Did a flight from Munich to Hamburg and back. Pushback at EDDM was with the DLH Livery, but the push at Hamburg EDDH was with the blank Livery. Is there something to change that the pushback at German Airports is everytime with the DLH Livery? 

Greetings

**Comment by skiselkov** [comment]
The reason why you were not getting the LEOS livery at EDDH is because in the real world LEOS doesn't provide ground services at EDDH. You can modify BP to give you LEOS at every German airport as follows:
1. open this file in a text editor such as Notepad: `objects/tugs/AST-3F.tug/liveries/LEOS.livery/info.cfg`
2. append a line saying: `icao "ED[A-Z]{2}"`
3. save the file

BP should now be offering you LEOS at every German airport. You will need to apply this change if you reinstall BP. I won't be incorporating this change into the standard version of BP, because it would be unrealistic.
