### ISSUE TITLE
JarDesign A330 V2.2RC1 - XP11 11.05r2 - BP v0.45 - Pushback didn't start (cold&dark)

### ISSUE THREAD

**Issue by dornus** [skiselkov/BetterPushbackC#168]
Hi,

I tryout Betterpushback  but I've some problems here because the Pushback didn't start correctly  if I go by cold and dark.

I prepare the A330 as usual and APU is running. 
Better Pushback told me that pushback is starting and give me the instruction to start Engines.
The Engines are running up but the Pushback didn't start even I turn OFF APU. Normally the electricity stays on with running engines but **with** BP the electricity seems to turned off. After complete pushback the electricity came back again. Without connected Tug the APU can be turned off/on as usual without loosing electricity.

See the Video for my (quick and dirty) cold and dark and PB procedure:
https://youtu.be/ESvra6QeirA

Kind Regards
Peter

JarDesign A330 V2.2RC1 - XP11 11.05r2 - BP v0.45

**Comment by dornus** [comment]
Hi,

unfortunately Version v0.46 didn't fix the problem on JarDesign A330.
Any Idea what is the problem here?

Kind Regards
Peter

**Comment by skiselkov** [comment]
I don't know what the electrical problem here is, but the reason it's not pushing you back is because you've got your landing lights on. BP simulates the driver being blinded and he won't move until you have them off. When you lost power, the landing lights turned off, so that's why it started to move.
With the landing lights off, does the airplane still lose power when being pushed back by BP0.46?

**Comment by dornus** [comment]
You're right. 
Maybe it was the same issue as with JD A320. Without landing light it's working now.
Thank you for your support!

Kind Regards
Peter
