### ISSUE TITLE
Very slowly tug

### ISSUE THREAD

**Issue by martin1006** [skiselkov/BetterPushbackC#170]
I really like this add-on. In fact it's the best one I've seen so far for pushbacks.

But.

My tug is very slowly. It's also not the standard pushbacktruck you see for large jets. I use this add-on with the SSG E170 jet.

If this problem can be solved it would be very nice.

Thanks in advance for the answers.

**Comment by skiselkov** [comment]
Hi

> My tug is very slowly

Can you please clarify at what slow speed it's going? A video would help. BP regulates it's speed backward to be approximately walking speed (4 km/h). Towing forward goes a lot faster (since the driver can more easily see what's ahead).

> It's also not the standard pushbacktruck you see for large jets.

I'm not sure what you mean. That the LEKTROs are not used for "large" jets such as the Embraer? I can assure you they are used all the time: https://youtu.be/5CBakINGRuE?t=3m49s

**Comment by martin1006** [comment]
Ah oke, didn't know this tow truck was frequently used.

Anyway. It seems I have to get used to the speed of the truck.

Great plugin by the way.

Regards
Martin

**Comment by skiselkov** [comment]
If you check out that video, you'll see a lektro tug towing an A320, so they are quite capable. The model in the plugin is a LEKTRO AP88, whis is rated up to 54,400 kg MTOW: http://www.lektro.com/series/ap88-series/
Anyway, glad I could help.
