### ISSUE TITLE
connecting tug first leads to disconnection of GPU and all services become unavailable in A320U

### ISSUE THREAD

**Issue by mishaikin** [skiselkov/BetterPushbackC#173]
Hi Saso!

I noticed today that when I chose connect tug first in A320U it disconnected the GPU and all service options became unavailable in the Service menu of the EFB. I disconnected the tug and they became available again.

Is it by design (for convenience :) )? Because this way it removes all pilot's responsibility to take care of those little things ....

**Comment by skiselkov** [comment]
This is not an accident. When a tug is connected, all other ground service connections MUST be removed as part of the departure check. That's why the driver says "all doors and hatches are closed". Otherwise I can guarantee you people would occasionally forget "that one last connection" and rip things off the airplane as soon as they start pushing.
