### ISSUE TITLE
Can't enable BetterPushback

### ISSUE THREAD

**Issue by PalmiFannar** [skiselkov/BetterPushbackC#207]
Hi, 
I've been trying now for a few days to install Better Pushback version 0.46 with no luck. I can see it in the plugin menu but I can't enable it (Nothing happens when I click it). 
In the Log.txt this is the error I'm getting "BetterPushback[airportdb.c:1786]: navdata error: it appears your simulator's navigation database is broken, or your simulator contains no airport scenery." 
I reinstalled XP11 but still having the same issue. 
  
Thanks 
Palmi

**Comment by Daveirving** [comment]
I have the same problem. This causes the navigraph cycle. Here a comment from navigraph:
"one hint ... possible you can check this with the devs ... we have changed the files/folder to lower-case ... you wrote, you use it on a Mac and Linux/Mac systems can be differ between lower/upper/mixed case. Therefore the suggestion to ask the devs of the addon, if they can change the files/folder to lower-case ... we need a common standard, because the current situation is very hard to support. One addon need lower case, one upper case, one mixed case ... sorry for the additional work for you!"

Dave

**Comment by skiselkov** [comment]
@Daveirving Thanks for the info, I will adapt my code to handle mixed case then and try to put up a build ASAP.

**Comment by skiselkov** [comment]
Please test out version 0.47.

**Comment by Daveirving** [comment]
0.47 works fine, also with navdata in lower case, thanks!

**Comment by skiselkov** [comment]
Glad I could help.
