### ISSUE TITLE
Cant set parking brake after pushback in zibo's 737 v 3.05g

### ISSUE THREAD

**Issue by thagreenkronic** [skiselkov/BetterPushbackC#24]
Unable to set parking brake after pushback using zibo's modified 737  version 3.05g. Not sure if this is an issue for you or zibo, but the only way to fix this atm is to quit the flight and restart without using betterpushback or the tug vehicle will never move off the front wheel.

**Comment by polt96** [comment]
exactly the same issue hear

**Comment by brenoperucchi** [comment]
On Zibo Release 3.05e I could complete the all operation with better pushback after that I unable to release the tug when the pushback stop reverse the aircraft

**Comment by skiselkov** [comment]
Have you first tried to contact Zibo to ask him about what changed between the versions? I know he doesn't use revision management software like GitHub, but he should be to able at least to tell you if he touched parking brake related code. BetterPushback doesn't do anything to the parking brake system other than ask it "parking brake on or off?". If BetterPushback can't detect the parking brake being set, then other things such as AutoGate won't either. So for now I'd consider that more a bug in the Zibo 737 rather than BetterPushback.
If Zibo didn't change anything in the 737, we can reopen this issue and I can attempt to repro & debug it.

**Comment by brenoperucchi** [comment]
Only to register here. 

There is hot fix for zibo: http://forums.x-plane.org/index.php?/forums/topic/111305-boeing-b738-800-modified/&page=382#comment-1213492

**Comment by skiselkov** [comment]
Thank you very much for the update, appreciate it.
