### ISSUE TITLE
Doesn't work with bigger aircrafts

### ISSUE THREAD

**Issue by Shain98** [skiselkov/BetterPushbackC#28]
Plugin doesn't work with the default 747 as well as with the FlightFactor a350XWB, it says "Pushback failure. No suitable tug for your aircraft."

**Comment by Shain98** [comment]
Ah, I just read through some of the other issues and I see that you are working now on getting the heavier aircrafts to work, sorry. And thank you for making this amazing plugin, it's the best pushback for X-Plane ever! Wish you the best.

**Comment by skiselkov** [comment]
Yep, your second comment is exactly spot on. The reason for this limitation is because the tugs have limitations in real life. The current AST-3F 210 model IRL can handle aircraft of up to 220t MTOW, 1m tire diameter and minimum landing gear leg length of about 0.5m. Anything outside these parameters cannot be handled. However, I should have the AST-1X 680 model ready within a day or two, which can handle any widebody up to the A380.
