### ISSUE TITLE
0.47 Not working, plugin disable in xplane

### ISSUE THREAD

**Issue by adixx328** [skiselkov/BetterPushbackC#284]
I have a problem with your plugin. its read by xplane but it shows itself as disabled and I cant turn it on. please help me.
![image](https://user-images.githubusercontent.com/38703522/68091942-3a60b580-fe86-11e9-950c-0083e1682e50.png)
Sorry for my english

**Comment by adixx328** [comment]
oh sorry wrong image
![image](https://user-images.githubusercontent.com/38703522/68091994-d1c60880-fe86-11e9-88ba-aa2082963a51.png)

**Comment by skiselkov** [comment]
Need the Log.txt from your simulator.

**Comment by adixx328** [comment]
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/3805055/Log.txt)

**Comment by skiselkov** [comment]
Here's the issue:
```
2019-11-04 16:33:21 BetterPushback[airportdb.c:1802]: navdata error: it appears your simulator's navigation database is broken, or your simulator contains no airport scenery. Please reinstall the database and retry.
```
I suspect the issue is in the installation path to X-Plane contains some special character in your username (``C:\Users\ada[]``) and that's confusing the plugin. As a temporary fix, you could try moving X-Plane to another folder on your drive, then launch it from there and seeing if it fixes the issue.

**Comment by adixx328** [comment]
no, still doesn't work

**Comment by adixx328** [comment]
It worked! I've just created a new user an it worked!
Thank you for help, great plugin.

**Comment by skiselkov** [comment]
Interesting, thanks for following up.
