### ISSUE TITLE
FlightFactor 757, no turns

### ISSUE THREAD

**Issue by Phil57** [skiselkov/BetterPushbackC#3]
First of all this plugin is amazing. Modelisation is perfect and the pushback choice is just so well done.

It works as expected with the default 737 but with the FF 757 it can't make turns. I've tried with the aircraft fully powered down and also powered up.

Not sure if you can do something about it because it's related to the aircraft.
Thanks.

**Comment by skiselkov** [comment]
This is a known issue. The FF 757 and 767 override nosewheel steering and BP can't take control of them. I'm working with the devs to get it sorted. I'll leave this issue open until it gets fixed.

**Comment by slgoldberg** [comment]
I noticed with nosewheel steering disabled (using the generic XP11 command ref to disable nosewheel steering), it does turn -- so maybe it's possible to correctly handle it with the plugin in that case?  However, it's pretty humorous when I do that; it just spins in fast circles as soon as I disable nosewheel steering. When I re-enable it, it can't always get back under control and pretty humorous things happen. :-) Anyway, it seems as if maybe the force parameters aren't correct for the case where the nosewheel steering is locked, i.e. it moves way too readily (seemingly without any resistance) and thus spins etc. Might be (?) easy enough to just tune the parameters in that case? I.e., the nosewheel seems to still turn freely.  To be clear, I think (correct me if I'm wrong) that disabling nosewheel steering on the FF 757-200 professional v2 does two things: (1) it simply ignores the nosewheel tiller, and (2) it kills the automatic connection between the nosewheel and the tail rudder -- i.e., using the pedals to nudge the plane left and right on the tarmac won't turn the nosewheel.  I use this on autoland since otherwise, the plane would depart the runway on autoland because the A/P is trying to keep the plane centered and gives rudder inputs, that translate to fast nosewheel changes which at >80 knots on the ground will wreak havoc. :-)

**Comment by skiselkov** [comment]
Ramzzess is working on this now, should be fixed soon.

**Comment by skiselkov** [comment]
Ramzzess released an update for the 757v2 and 767 which addresses the incompatibility. Please test with BetterPushback v0.29, should now be fully functional.

**Comment by JetNoise61** [comment]
Tested it today FF B757, works without problems, as of now. Thank you.

**Comment by skiselkov** [comment]
@JetNoise61 Thank you for testing. Closing it now.

**Comment by slgoldberg** [comment]
Sorry I missed the window to test this for you .. my bad, work has been intense. Anyway, thanks so much -- it is working great.  (I hope adding this comment doesn't reopen.)
