### ISSUE TITLE
Plane Request

### ISSUE THREAD

**Issue by Thalios** [skiselkov/BetterPushbackC#32]
Would it be possible for you to add the PMDG Douglas DC-6 please? I love your plugin but can't use it with my favorite vintage plane.

**Comment by skiselkov** [comment]
I will investigate this. The DC-6 has a single-wheel nose gear, which none of the Goldhofer tractors support. I plan on adding a smaller bizjet- and turboprop-class tractor in the future, which should provide support for the DC-6's unusual (by modern standards) nose gear arrangement.

**Comment by Thalios** [comment]
Thank you so much! Your plugin has made my sim life a lot more immersive and enjoyable.

**Comment by skiselkov** [comment]
Glad you like it. The tug I plan to add for this is an lithium-ion battery-powered electric tug. It'll be a fun contrast with the old gas-guzzling, smoke-spewing, oil-dripping radials of the DC-6 :)

**Comment by skiselkov** [comment]
Making good progress on this, should have something test-ready in a few days.
![ap88](https://user-images.githubusercontent.com/3300688/28487529-a5117184-6e92-11e7-94cc-25787d95afcf.png)

**Comment by birdydma** [comment]
This one ready for a tug race.

https://www.youtube.com/watch?v=P27oVdvb3Z8

**Comment by Thalios** [comment]
Waouh! That fast?! The 3D model looks great already. 👍 

And that race.... OMG! ^.^

> This one ready for a tug race.
> 
> https://www.youtube.com/watch?v=P27oVdvb3Z8

**Comment by skiselkov** [comment]
Please test with the latest release, which includes the AP88 model.

**Comment by Thalios** [comment]
Same thing as before I'm afraid: "Pushback failure. No suitable tug for your aircraft."

**Comment by skiselkov** [comment]
Can you attach the Log.txt from the run? It should contain a reason that explains to me which aircraft parameter was out of bounds for all tugs.

**Comment by Thalios** [comment]
Here you go ^.^


[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/1170905/Log.txt)

**Comment by skiselkov** [comment]
It's as I suspected. I'm not sure I'm gonna be able to fix this to your satisfaction. The problem basically amounts to the fact that the DC-6's nose wheel is just so freakin' large. It has an outer tire diameter of almost 1.2 meters. That's more than the AST-3F can handle and it would absolutely dwarf the AP88. And while the AST-1X can handle that tire size, it can't normally handle single-tire landing gear (because of its two-arm grasping mechanism, which relies on there being two wheels side-by-side to grab onto).
I do however have a workaround for you. If you don't mind the tug looking somewhat wrong, you can modify the AST-1X config file in "`objects/tugs/AST-1X.tug/info.cfg`" by appending the following two lines to it:
```
min_mtow 40000
gear_compat ff
```
This removes the gear-compatibility check and lowers the minimum allowable aircraft MTOW of the AST-1X from the normal 150 tons to just 40 tons. This should make BP happy to give you the AST-1X model. The underlying towing algorithm isn't dependent on the actual tug model used - that's just eye candy.
You will have to re-edit this file after a plugin update, but at this stage this is the best I can do for a compatibility workaround.

**Comment by Thalios** [comment]
That's plenty fine for me. Thank you very very much!

**Comment by Thalios** [comment]
It does work, so thanks you very much again. Only trouble is that it doesn't seem to follow the plan and seems very very slow. On the other hand, I can guide it with rudder controls so that's plenty good enough for me. Thanks again o/
