### ISSUE TITLE
Sound problems and BP not enabled.

### ISSUE THREAD

**Issue by AndrewICT** [skiselkov/BetterPushbackC#328]
I feel like this has to do something with me switching back and forth between XP Beta and XP11 on steam but now I'm experiencing issues with BP. Sometimes I'll get audio initialization issues and even in the plugin admin page, BP is there, but when I click to enable it, it freezes but nothing else ha
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/4762984/Log.txt)
ppens.

**Comment by theduusK** [comment]
Got the same issue since a few weeks und trying around since a few days.
Already tried to try different BP versions (0.47 / 0.48), deleted XP-Preferences (/output/preferences),
checked / repaired XP files via Steam, checked my sound devices (also deactivated the exclusive mode).
Sometimes XP does not have audio at all, after a restart it works again, but BP is never working.
The plugin gets listed in the plugin admin list, but I'm not able to activate it.

```
2020-07-06 18:21:09 BetterPushback[xplane.c:539]: This is BetterPushback-v0.48 libacfutils-0e818a4
Loaded: G:\Steam/steamapps/common/X-Plane 11/Resources/plugins/BetterPushback/64/win.xpl (skiselkov.BetterPushback).
[...]
2020-07-06 18:21:21 BetterPushback[wav.c:224]: Cannot init audio system: device open failed.
```
- i9-9900K
- 32 GB RAM
- GeForce GTX 1080 (latest studio driver)
- Windows 10 Pro (up 2 date)
- X-Plane 11.50b11 (same issue on stable version)

I'm not quite sure, but somehow I think it could be related to the OpenAL driver.
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/4888997/Log.txt)

**Comment by AndrewICT** [comment]
SOLVED, right-click on the sound setting, go to sound settings and scroll down to app volumes and change X-Plane's default output to default. Mine was blank and it solved both issues, including the sound system for x plane!

**Comment by theduusK** [comment]
Maaan thanks a lot - you are my hero 👍 
Exact the same issue on my side. Empty output device in App settings although the X Plane sounds worked fine.
Now BP works fine as well! Thanks!
