### ISSUE TITLE
Texture Regions AST-3F

### ISSUE THREAD

**Issue by AirLuSa** [skiselkov/BetterPushbackC#40]
Hej,
 congrats to this perfect pushback plug-in. I tried to repaint the AST-2 truck to fit the Lufthansa LEOS paintsheme, but the logo is mirrored on one side due to the fact, that the texture region is not set correctly. See attached picture. Is it possible to change/fix it? Due to the fact I am not used to blender I tried to change it myself with AC3D, but than the lights in the object file are getting corrupted. 
![ast-2](https://user-images.githubusercontent.com/30418648/28541696-416b49e6-70ba-11e7-9e0c-7f6cf3d03740.png)

Thanks
Lukas

**Comment by skiselkov** [comment]
I'll get right to it, shouldn't be hard to fix. I also need to work on airport-texture support. Right now the airport-specific textures feature is kind of crudely hacked in place.

**Comment by AirLuSa** [comment]
Wow, thanks for the fast response for fixing. I've checked the AST-1 truck too, the obj file doesn't differ between left and right side either, so if you want to make airport texture possible it would be nice to get left and right side of the trucks separated. Then there won't be a limit in customization ;-)

**Comment by skiselkov** [comment]
Ok I've split all models up and moved the UVs for the right side so that you can do separate texturing for them. The AST-3F's texture file is kind of a mess right now, but I don't think much new modeling will need to be done on it (plus there's a bunch of UV mapping efficiencies that could be had, no doubt). You don't need to restart your texturing work. I've separated the right-side UVs into separate layers with "(right)" in the name so you only have to copy those over.

**Comment by skiselkov** [comment]
Oh and one more thing, if you are applying solid color stripes (like the yellow ones above), don't paint into a top layer, paint into a layer just above the "base paint" (the bottom most). That way all the hand-painted grime, ambient occlusion and seams will appear properly above your new paint layer. It goes without saying that you shouldn't be painting into the PNGs. Grab the original Gimp XCFs from the repo and paint into those.
I'll do some more coding work in the plugin so that it more properly automatically selects the appropriate tug livery based on location. I'll let you know where and how to place your output files once I'm done.

**Comment by AirLuSa** [comment]
Perfect, will test the paint files in the afternoon. Yeah it was just a quick and dirty paint to see what's possible. :-)

**Comment by skiselkov** [comment]
So I've built in a new method of shipping liveries with the tug that is geo-sensitive. Every tugs' file hierarchy looks like this now:
```
<TUGNAME>.tug
  + liveries
    + <LIVERYNAME>.livery
      + info.cfg            <- defines where the livery applies
      + <texture>.dds       <- texture file, exact filename depends no tug model
```
Right now every tug comes with a `generic.livery`, which is applied in case there is no location-specific livery. To create a location-specific livery, simply create a new folder under `liveries` (for example `LEOS.livery`), put in the appropriate texture files (they need to have the same names as in the `generic.livery`, as that's what's defined in the OBJ file) and write an `info.cfg` file. An example of a simple `info.cfg` file:
```
icao "EDDF"        # Apply livery if nearest airport to aircraft is EDDF
icao "EDDM"        # You can have multiple "icao" lines to match multiple airports.
icao "ED[A-Z]{2}"  # The ICAO selector supports Perl-style regular expression matching.
```
I don't expect you to know the nuances of how to do all of this, so I've prepared an empty `LEOS.livery` skeleton for you and attached it below. Use this in your copy of BetterPushback for testing. When you are done with the repaints, I can commit your texture files to the repository, or if you are familiar with Git & Github, you can send me a merge request (an inactive `LEOS.livery` is already in the repo, ready to receive your files). That way I can build & ship your textures with the plugin at the same time.
[LEOS.livery.zip](https://github.com/skiselkov/BetterPushbackC/files/1172790/LEOS.livery.zip)

**Comment by skiselkov** [comment]
Btw: for right now, I'd recommend only doing the AST-3F repaint. The AST-1X model is incomplete and the textures need a lot more work. The version of it right now in the plugin is just an initial minimally functional attempt to allow people to fly widebodies. I need to rework the model of the grabbing mechanism, add a cab & driver and do a bunch more animation work.

**Comment by AirLuSa** [comment]
Okay, painted the AST-3F into the LEOS colours. But I noticed that in the textures including now separated places for left and right, but the object of the latest release still uses only one of the texture regions.

Livery selection works very well with XP-10. Cool feature. Config file is also easy to understand.
[LEOS.livery.zip](https://github.com/skiselkov/BetterPushbackC/files/1172939/LEOS.livery.zip)

**Comment by skiselkov** [comment]
I had to pull the build with the side-separation due to a problem in the Windows version. Please try with v0.27. Thanks for adding Hannover to the airport. Btw: careful when you're adding quote marks in the info.cfg. I noticed your text editor added the German version which has a different symbol for the closing quote (because in German the quotes are directional). The parser however strictly expects to only see the simple " character. See attached info.cfg. With this in place and the latest built, it works for me (tried at EDDF).
[info.cfg.zip](https://github.com/skiselkov/BetterPushbackC/files/1173110/info.cfg.zip)

**Comment by AirLuSa** [comment]
Okay no problem. Yeah I've noticed that already, though I had copied the ones. But yes I changed it and forgot to copy the right ones. So here is an update also to the textures. I accidentally removed the background fro the goldhofer logo, resulting in not good looking logo on the door.
[LEOS.livery.zip](https://github.com/skiselkov/BetterPushbackC/files/1173120/LEOS.livery.zip)

**Comment by skiselkov** [comment]
Great stuff. Can I add your real name to the copyright notice on the paint files? If so, what is your real name please?

**Comment by skiselkov** [comment]
Btw: while it's not difficult to flip the UVs, it's quite a bit more complicated to flip all the base paint layers on the pre-existing texture. Could you instead please simply horizontally flip text left-to-right while exporting? That should be fairly easy to do.

**Comment by skiselkov** [comment]
Sorry for misunderstanding your comment at first. The text still needs to be flipped, but I also forgot to export the AST-3F model with the modified UVs to OBJ form, so that's why it still appears to be flipped. I'll have a fixed version ready for you shortly.

**Comment by skiselkov** [comment]
Ok, so I've incorporated this texture & livery into the tug (v0.28). I've flipped the text on the affected panel myself as it was fortunately not covered by any other layer. I've also fixed the AST-3F UVs. Another feature I've implemented is that you can omit the LIT texture in the livery pack. Any missing files are pulled from the `generic.livery`. This cuts down on the resulting plugin size a lot, since DDS files take up a lot of space.

**Comment by AirLuSa** [comment]
Perfect Idea with the _Lit file. Thanks for editing and adding the paint files. As soon you'll have the other trucks ready. I will paint them to LEOS also, but take you're time.

**Comment by skiselkov** [comment]
Ok, I'll close this for now. Once the AST-1X is finished, feel free to open a one.
