### ISSUE TITLE
BetterPushback not working on the Zibo 737

### ISSUE THREAD

**Issue by InfinitePower563** [skiselkov/BetterPushbackC#477]
Installed version: [Zibo 737 compatibility workaround](https://github.com/skiselkov/BetterPushbackC/releases/tag/v0.50)
OS: Windows 10
Simulator: X-Plane 12.05r1
Aircraft: Zibo 737-800 4k version v4.0
Description: When attempting to open the "plan pushback" menu, X-Plane freezes and crashes without opening the menu.

Log: 
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/11872778/Log.txt)

**Comment by joetank390** [comment]
My log.txt says the same as yours. 
[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/11929665/Log.txt)

**Comment by DiamondPG** [comment]
The log says that the plugin tries to write to an unwritable data ref. The end of the log states a bunch of weather errors.

BetterPushback[acf_outline.c:217]: Error parsing acf file: property _wing/7/_Croot not found
2023-06-26 13:41:15 BetterPushback[acf_outline.c:81]: Error parsing acf file: property _body/0/_r_dim not found
[BetterPushback-v0.50]: Dataref 'sim/weather/visibility_reported_m' has been replaced. Please use the new name.
[BetterPushback-v0.50]: Dataref 'sim/weather/cloud_type[0]' has been replaced. Please use the new name.
[BetterPushback-v0.50]: Dataref 'sim/weather/cloud_type[1]' has been replaced. Please use the new name.
[BetterPushback-v0.50]: Dataref 'sim/weather/cloud_type[2]' has been replaced. Please use the new name.
[BetterPushback-v0.50]: Dataref 'sim/weather/use_real_weather_bool' has been replaced. Please use the new name.
2023-06-26 13:41:15 BetterPushback[dr.c:96]: assertion "dr->writable" failed: dataref "sim/weather/use_real_weather_bool" is not writable (bp_cam.c:1200: &drs.use_real_wx)
--=={This application has crashed because of the plugin: BetterPushback-v0.50}==--

Try updating or reinstalling

**Comment by joetank390** [comment]
Thank you for commenting. I have reinstalled it again today and it still CTD. the log goes on about a terrain problem now.

Here is a copy of the log.

[Log.txt](https://github.com/skiselkov/BetterPushbackC/files/12302124/Log.txt)

**Comment by joetank390** [comment]
I will look into them and see what I can find.

IVAO, will no I have a lot of follow me vic doing some pretty odd stuff. it seems unable to read the aircraft ids and then convert them to the right image.

**Comment by InfinitePower563** [comment]
Fixed: Updated Zibo and used the latest snapshot of BetterPushbackC
