### ISSUE TITLE
Zibo's 738 no turns

### ISSUE THREAD

**Issue by copyyy** [skiselkov/BetterPushbackC#5]
Thought it'd be nice to have this as a seperate open issue rather than just replying it to the FF 757 issue.

As said in the title, it's not turning in the 738 with Zibo's modification:
http://forums.x-plane.org/index.php?/forums/topic/111305-boeing-b738-800-modified

Edit: You'll most likely want to try with the setting "TOE BRAKE AXIS" in the FMC turned on and off because Zibo does some stuff :P

**Comment by skiselkov** [comment]
Thanks for the info. I'll investigate shortly. Zibo probably doesn't let BP override nosewheel steering, so it can't turn.

**Comment by skiselkov** [comment]
This is an internal problem in Zibo's modified 737. It forcibly overrides wheel steering and doesn't let anything else take over. I've submitted a patch to Zibo to rectify this and Zibo has published a temporary workaround: http://forums.x-plane.org/index.php?/forums/topic/111305-boeing-b738-800-modified/&do=findComment&comment=1211370
I'm going to close this issue as "wontfix", because there's frankly nothing BetterPushback can do differently to resolve this incompatibility.
