### ISSUE TITLE
Friend couldnt turn on plugin

### ISSUE THREAD

**Issue by thagreenkronic** [skiselkov/BetterPushbackC#56]
I was helping someone install this plugin and told them to get the latest version, v0.31.
Upon installing the plugin was turned off by default in the plugin admin menu and pressing the checkbox did nothing. No green tick came up.
I updated to the latest version from v0.28 and it worked fine for me.
So I told him to downgrade to v0.28, since that was the last one I tried, and it worked fine for him.

Seems if you have never had a previous version installed and try to install 0.31 it wont let you turn it on, but having a previous version and then updating works fine because it was already on? (Cant confirm that because he didnt want to update from 0.28 again)

**Comment by skiselkov** [comment]
Can you please confirm that he was *definitely* running version `0.31` and not `0.30`? There was a bug in `0.30` which could cause the problem you're describing, which is why I pushed out `0.31` as soon as possible. If you have the `Log.txt` from your friend, that would be very helpful.
I will be publishing a new version (`0.32`) in about 30 minutes. If you could test with that and report back to me, that would be great. If it still doesn't work, please make sure to include the `Log.txt`, otherwise I cannot be sure where to start looking.

**Comment by skiselkov** [comment]
Please test with `v0.32` and report back how it went.

**Comment by thagreenkronic** [comment]
Im sorry, I only know him from a xplane facebook group and not in RL. Perhaps he did download the wrong one. I did ask him to continue testing after v0.28 worked for him by updating again and seeing if it worked but he did not seem interested, he was just happy to have it working.

**Comment by skiselkov** [comment]
Closing as invalid then.
