### ISSUE TITLE
A350 Problem is back

### ISSUE THREAD

**Issue by Milki52** [skiselkov/BetterPushbackC#71]
Hey,
during work i have missed a lot of your Updates. Today i wanted to fly again with the a350 from othh. I updated to 0.37 and the problem is back. A350 is not pushing. Any Solutions? The Plugin has changed a lot since 0.22, great work!

**Comment by skiselkov** [comment]
I'm not at my machine right now, but I'll investigate in a few hours and check what's going on.

**Comment by skiselkov** [comment]
Please test on v0.38. As you can see below, I can't reproduce the problem, everything works perfectly OK (tested both with and without engines running during pushback).
![shot](https://user-images.githubusercontent.com/3300688/28999977-730bbc28-7a5c-11e7-841a-06899c91ad0b.png)

**Comment by Milki52** [comment]
okay, what i found out, the tow only disconnects when the plane is pressurized on the hydraulics. When the pumps are not on, the tow doesnt disconnect. On 0.38 the PB works well at the moment. Thanks :)

**Comment by skiselkov** [comment]
That's because the A350 simulates lack of brake pressure by refusing to set the dataref park_brake=1 when no hydraulic pressure is present. You shouldn't be towing your aircraft with the hydraulics depressurized in the real world anyway! It would mean your parking brake is ineffective and you'll simply roll away as soon as the tow disconnects (and you'll quite possible roll **into** the tow).
