### ISSUE TITLE
Default view after accepting PB plan

### ISSUE THREAD

**Issue by jfjoubert** [skiselkov/BetterPushbackC#78]
Hi Saso,

Nothing major but I see that whenever you accept (or even cancel by escaping) a PB plan then the sim will return you to the default captains view. Would it be possible to "remember" the current user specified camera viewpoint when returning from the planning screen?

Jean

**Comment by skiselkov** [comment]
This is unfortunately a known issue due to a quirk in the SDK which doesn't allow me to change one parameter of the view coordinate system. As a consequence, BP must manually issue a view command for a know good "view type" when doing the pushback planner. Unfortunately, this then eliminates the ability of BP to return the view type to you exactly as it was left before and I've not found a way around this yet.

**Comment by jfjoubert** [comment]
No problem... thanks for the feedback.
